export const
  CAMPAIGN_SAVE = 'CAMPAIGN_SAVE',

  NODE_SAVE = 'NODE_SAVE',
  NODE_DELETE = 'NODE_DELETE',
  NODE_ADD = 'NODE_ADD',
  NODE_EDIT = 'NODE_EDIT',
  NODE_CHANGE = 'NODE_CHANGE',

  BLOCK_ADD = 'BLOCK_ADD';