---

- name: Setup uWSGI
  sudo: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python
  tags: ['uwsgi']

- name: Ensure uwsgi/run dir has correct permissions so we can create socket without sudo perms
  sudo: yes
  file:
    path: '{{ item.path }}'
    state: '{{ item.state}}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  with_items:
    - path: /var/run/uwsgi
      owner: www-data
      group: www-data
      state: directory
      recurse: yes
      mode: '0755'
  tags: [ 'uwsgi' ]

- name: Start uWSGI
  sudo: yes
  service:
    name: '{{ item }}'
    state: started
  with_items:
    - uwsgi
  tags: ['uwsgi']
